[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Serial monitor
monitor_speed = 921600
monitor_filters = direct

; Build settings
build_flags =
    -DCORE_DEBUG_LEVEL=0

; Library dependencies
lib_deps =
    ESP32Servo
    WiFi
